sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
secure: "ZPTokHsJs6NtWFhUyG5GH0YnS+eE/6HvfnKZjoynF1uA51+SY2wp4tMoE5y2j2VFDBa0DBeKRChdzDSMhjZQDXqUWNzv+AObdzOlVJqovdQgBcwcENB9bD1MF6ZRSpol7ETi5lDkCH3fpi7RG/gb9HIyb1F63tzo5DXewfXOUlk="
